server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: loveai
  profiles:
    active: local

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG